# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

### datasource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myLearn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


logging:
  file: /logs/myLearn/springboot/springboot.log
  pattern:
    #yml文件中首尾加上单引号可解决识别不了%的问题，properties不需要加
#    %-d{yyyy-MM-dd HH:mm:ss} [%c-%L]-[%p] %m %n
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] [%c-%L]-[%p] - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] [%c-%L]-[%p] - %msg%n'
